DECLARE

	V_NOME TBNOME.NOME%TYPE;
	...
	...
	...
	CURSOR CURSOR_NOME IS
		SELECT NOME,TBNOME2.NOME,.... FROM TBNOME1
		INNER JOIN TBNOME2 ON (TBNOME1.NOME = TBNOME2.NOME);
BEGIN
	OPEN CURSOR_NOME;		
  	LOOP	
   		FETCH CURSOR_NOME INTO VARIAVEIS;
   		EXIT WHEN CURSOR_NOME%NOT_FOUND;
   		CALCULOS
   		IF CONDICAO THEN
    			.....
   		ELSEIF CONDICAO THEN
    			.....
   		END IF;
   		INSERT INTO TBNOME3 VALUES VARIAVEIS;
  	END LOOP;
  	COMMIT;
 	CLOSE CURSOR_NOME;
END;